In [1]:
# imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
# show all columns in the df when printing to screen
pd.options.display.max_columns = None

In [2]:
# load csv file (200k results)
df = pd.read_csv("../petfinder_data/favorites_sample_small.csv", sep=";")

# remove all duplicate versions of a pet
df.drop_duplicates(subset=['id'], keep="first", inplace=True)
df

user_id         favorited_at        id  organization_id  \
0       4369629  2020-01-01 00:00:04  46861637            44719   
1       4369629  2020-01-01 00:00:07  46898514            35651   
2       4112169  2020-01-01 00:00:08  46980809            40518   
3       4369680  2020-01-01 00:00:12  46956517            29207   
4       4369681  2020-01-01 00:00:13  46860620            48762   
...         ...                  ...       ...              ...   
140953  4260498  2020-01-05 02:43:16  47025142            26948   
140956  4397520  2020-01-05 02:43:17  46710925            43609   
140959  3980474  2020-01-05 02:43:19  47030490            27014   
140961  4260498  2020-01-05 02:43:21  47024824            32882   
140963  4260498  2020-01-05 02:43:24  47024649            26377   

        organization_active  organization_enabled organization_display_id  \
0                         1                     1                  OH1073   
1                         1                     1                   OH745   
2                         1                     1                  NY1044   
3                         1                     1                   FL806   
4                         1                     1                   TN914   
...                     ...                   ...                     ...   
140953                    1                     1                  CA1110   
140956                    1                     1                  OH1043   
140959                    1                     1                    CA12   
140961                    1                     1                   MO380   
140963                    1                     1                   AR224   

        import_on                     import_software  \
0               0                                 NaN   
1               0                                 NaN   
2               0                                 NaN   
3               0                                 NaN   
4               1  Petfinder Import Standard Template   
...           ...                                 ...   
140953          1                           Chameleon   
140956          0                                 NaN   
140959          0                                 NaN   
140961          0                                 NaN   
140963          0  Petfinder Import Standard Template   

                  organization_type     location_type  is_public_location  \
0       Rescue Group / Foster-Based  Default Location                   0   
1       Rescue Group / Foster-Based  Default Location                   1   
2       Rescue Group / Foster-Based  Default Location                   0   
3                               NaN  Default Location                   1   
4       Rescue Group / Foster-Based       Foster Home                   0   
...                             ...               ...                 ...   
140953       Private Animal Shelter  Default Location                   1   
140956     Municipal Animal Shelter  Default Location                   1   
140959  Rescue Group / Foster-Based  Default Location                   0   
140961  Rescue Group / Foster-Based       Foster Home                   0   
140963       Private Animal Shelter  Default Location                   1   

       state_code country_code adoption_status           created_at  \
0              OH           US       Adoptable  2019-12-16 15:06:18   
1              OH           US       Adoptable  2019-12-20 02:58:49   
2              NY           US         Adopted  2019-12-31 18:24:35   
3              FL           US       Adoptable  2019-12-28 07:50:35   
4              CT           US       Adoptable  2019-12-16 07:30:36   
...           ...          ...             ...                  ...   
140953         CA           US       Adoptable  2020-01-04 15:57:01   
140956         OH           US         Adopted  2019-11-29 05:04:03   
140959         CA           U

In [3]:
# replace both 'pet_description' and 'pet_description_length' columns with a new column 'has_description'
def create_has_description(row):
    # compare on 'pet_description' field
    # the 'pet_description_length' field uses both 0.0 and nan for a pet with no description
    if pd.isnull(row['pet_description']):
        return 0
    else:
        return 1
df['has_description'] = df.apply(lambda row: create_has_description(row), axis=1)
# verify flag is working properly
df[['has_description', 'pet_description']]

has_description                                    pet_description
0                     1  Meet Elsa!Elsa came to us as a stray. She had ...
1                     1  Coco came into the rescue a couple years ago w...
2                     1  AGE: 1 YearSEX: Neutered MaleWEIGHT: 50 Pounds...
3                     1  Very sweet puppy will neuter micrchip and give...
4                     0                                                NaN
...                 ...                                                ...
140953                0                                                NaN
140956                1  Walter is a feisty young guy! If you're lookin...
140959                1  NOTE: This is a courtesy posting for another r...
140961                1  Please note Margo is located in Denver, Colora...
140963                1  If you can see this dog, she is AVAILABLE. We ...

[63307 rows x 2 columns]

In [4]:
# drop columns that the model will not train on
to_drop = [
    'adoption_fee',
    'adoption_fee_waived',
    'adoption_status',
    'country_code',
    'created_at',
    'display_adoption_fee',
    'favorited_at',
    'good_with_others_notes',
    'id',
    'import_on',
    'import_software',
    'is_public_location',
    'latitude',
    'location_type',
    'longitude',
    'name',
    'num_aifs',
    'organization_active',
    'organization_animal_identifier',
    'organization_display_id',
    'organization_enabled',
    'organization_id',
    'organization_type',
    'pet_description',
    'pet_description_length',
    'postal_code',
    'published_date',
    'secondary_breed',
    'secondary_color',
    'special_needs_notes',
    'species',
    'state_code',
    'tags',
    'tertiary_color',
    'unknown_breed',
    'updated_at',
    'user_id'
]
df.drop(to_drop, axis=1, inplace=True)

In [5]:
# fill nan values in all color fields
df['primary_color'].fillna(value='NO_PRIMARY_COLOR', inplace=True)
# fill nan values in for coat_length
df['coat_length'].fillna(value='NO_COAT_LENGTH', inplace=True)
df.head()

mixed_breed    age animal_type                   primary_breed  \
0            1   Baby         Dog                Pit Bull Terrier   
1            1  Young         Dog                Pit Bull Terrier   
2            0  Young         Dog              Labrador Retriever   
3            1   Baby         Dog             German Shepherd Dog   
4            0   Baby         Dog  American Staffordshire Terrier   

      primary_color  gender    size     coat_length good_with_children  \
0  NO_PRIMARY_COLOR  Female  Medium           Short            unknown   
1  NO_PRIMARY_COLOR  Female  Medium  NO_COAT_LENGTH                yes   
2  NO_PRIMARY_COLOR    Male  Medium          Medium                yes   
3  NO_PRIMARY_COLOR    Male   Large          Medium                yes   
4  NO_PRIMARY_COLOR  Female   Small  NO_COAT_LENGTH            unknown   

  good_with_dogs good_with_cats good_with_other_animals  house_trained  \
0            yes        unknown                 unknown              0   
1            yes             no                 unknown              0   
2            yes            yes                 unknown              1   
3            yes            yes                 unknown              0   
4        unknown        unknown                 unknown              0   

   altered  declawed  special_needs  shots_current  num_photos  num_videos  \
0        1         0              1              1           5           0   
1        1         0              0              1           2           0   
2        1         0              0              1           6           0   
3        0         0              0              1           1           0   
4        0         0              0              0           3           0   

   has_description  
0                1  
1                1  
2                1  
3                1  
4                0

In [6]:
# validate all columns have 63,307 non-null values
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 63307 entries, 0 to 140963
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   mixed_breed              63307 non-null  int64 
 1   age                      63307 non-null  object
 2   animal_type              63307 non-null  object
 3   primary_breed            63307 non-null  object
 4   primary_color            63307 non-null  object
 5   gender                   63307 non-null  object
 6   size                     63307 non-null  object
 7   coat_length              63307 non-null  object
 8   good_with_children       63307 non-null  object
 9   good_with_dogs           63307 non-null  object
 10  good_with_cats           63307 non-null  object
 11  good_with_other_animals  63307 non-null  object
 12  house_trained            63307 non-null  int64 
 13  altered                  63307 non-null  int64 
 14  declawed                 63307 non-nu

In [7]:
# convert all 'good_with_xxx columns' to 0 or 1 (include unknown with 0)
# replace both 'pet_description' and 'pet_description_length' columns with a new column 'has_description'
def convert_to_bin(row, col):
    # compare on 'pet_description' field
    # the 'pet_description_length' field uses both 0.0 and nan for a pet with no description
    if row[col] in ["no", "unknown"]:
        return 0
    else:
        return 1
df['good_with_children'] = df.apply(lambda row: convert_to_bin(row, "good_with_children"), axis=1)
df['good_with_dogs'] = df.apply(lambda row: convert_to_bin(row, "good_with_dogs"), axis=1)
df['good_with_cats'] = df.apply(lambda row: convert_to_bin(row, "good_with_cats"), axis=1)
df['good_with_other_animals'] = df.apply(lambda row: convert_to_bin(row, "good_with_other_animals"), axis=1)
df.head()

mixed_breed    age animal_type                   primary_breed  \
0            1   Baby         Dog                Pit Bull Terrier   
1            1  Young         Dog                Pit Bull Terrier   
2            0  Young         Dog              Labrador Retriever   
3            1   Baby         Dog             German Shepherd Dog   
4            0   Baby         Dog  American Staffordshire Terrier   

      primary_color  gender    size     coat_length  good_with_children  \
0  NO_PRIMARY_COLOR  Female  Medium           Short                   0   
1  NO_PRIMARY_COLOR  Female  Medium  NO_COAT_LENGTH                   1   
2  NO_PRIMARY_COLOR    Male  Medium          Medium                   1   
3  NO_PRIMARY_COLOR    Male   Large          Medium                   1   
4  NO_PRIMARY_COLOR  Female   Small  NO_COAT_LENGTH                   0   

   good_with_dogs  good_with_cats  good_with_other_animals  house_trained  \
0               1               0                        0              0   
1               1               0                        0              0   
2               1               1                        0              1   
3               1               1                        0              0   
4               0               0                        0              0   

   altered  declawed  special_needs  shots_current  num_photos  num_videos  \
0        1         0              1              1           5           0   
1        1         0              0              1           2           0   
2        1         0              0              1           6           0   
3        0         0              0              1           1           0   
4        0         0              0              0           3           0   

   has_description  
0                1  
1                1  
2                1  
3                1  
4                0

In [8]:
# encode 'age' column manually since we want a speficic order
# order: ["Baby", "Young", "Adult", "Senior"]

def encode_age(row):
    if row["age"] == "Baby":
        return 0
    elif row["age"] == "Young":
        return 1
    elif row["age"] == "Adult":
        return 2
    else:
        # senior pets
        return 3

df['age'] = df.apply(lambda row: encode_age(row), axis=1)
df.head()

mixed_breed  age animal_type                   primary_breed  \
0            1    0         Dog                Pit Bull Terrier   
1            1    1         Dog                Pit Bull Terrier   
2            0    1         Dog              Labrador Retriever   
3            1    0         Dog             German Shepherd Dog   
4            0    0         Dog  American Staffordshire Terrier   

      primary_color  gender    size     coat_length  good_with_children  \
0  NO_PRIMARY_COLOR  Female  Medium           Short                   0   
1  NO_PRIMARY_COLOR  Female  Medium  NO_COAT_LENGTH                   1   
2  NO_PRIMARY_COLOR    Male  Medium          Medium                   1   
3  NO_PRIMARY_COLOR    Male   Large          Medium                   1   
4  NO_PRIMARY_COLOR  Female   Small  NO_COAT_LENGTH                   0   

   good_with_dogs  good_with_cats  good_with_other_animals  house_trained  \
0               1               0                        0              0   
1               1               0                        0              0   
2               1               1                        0              1   
3               1               1                        0              0   
4               0               0                        0              0   

   altered  declawed  special_needs  shots_current  num_photos  num_videos  \
0        1         0              1              1           5           0   
1        1         0              0              1           2           0   
2        1         0              0              1           6           0   
3        0         0              0              1           1           0   
4        0         0              0              0           3           0   

   has_description  
0                1  
1                1  
2                1  
3                1  
4                0

In [9]:
# encode 'animal_type' column
animal_type_enc = LabelEncoder()
# can later use animal_type_enc like so animal_type_enc.inverse_transform([2]) to get original type
df['animal_type'] = animal_type_enc.fit_transform(df['animal_type'].values)

# encode 'primary_breed' column
breed_enc = LabelEncoder()
df['primary_breed'] = breed_enc.fit_transform(df['primary_breed'].values)

# encode 'primary_color' column
color_enc = LabelEncoder()
df['primary_color'] = color_enc.fit_transform(df['primary_color'].values)

# encode 'gender' column
gender_enc = LabelEncoder()
df['gender'] = gender_enc.fit_transform(df['gender'].values)

# encode 'coat_length' column
coat_length_enc = LabelEncoder()
df['coat_length'] = coat_length_enc.fit_transform(df['coat_length'].values)

df.head()

mixed_breed  age  animal_type  primary_breed  primary_color  gender  \
0            1    0            3            292             48       0   
1            1    1            3            292             48       0   
2            0    1            3            218             48       1   
3            1    0            3            169             48       1   
4            0    0            3             20             48       0   

     size  coat_length  good_with_children  good_with_dogs  good_with_cats  \
0  Medium            5                   0               1               0   
1  Medium            4                   1               1               0   
2  Medium            3                   1               1               1   
3   Large            3                   1               1               1   
4   Small            4                   0               0               0   

   good_with_other_animals  house_trained  altered  declawed  special_needs  \
0                        0              0        1         0              1   
1                        0              0        1         0              0   
2                        0              1        1         0              0   
3                        0              0        0         0              0   
4                        0              0        0         0              0   

   shots_current  num_photos  num_videos  has_description  
0              1           5           0                1  
1              1           2           0                1  
2              1           6           0                1  
3              1           1           0                1  
4              0           3           0                0

In [10]:
# encode 'size' column manually since we want a speficic order
# order: ["Baby", "Young", "Adult", "Senior"]

def encode_size(row):
    if row["size"] == "Small":
        return 0
    elif row["size"] == "Medium":
        return 1
    elif row["size"] == "Large":
        return 2
    else:
        # Extra Large Pets
        return 3

df['size'] = df.apply(lambda row: encode_size(row), axis=1)
df.head()

mixed_breed  age  animal_type  primary_breed  primary_color  gender  size  \
0            1    0            3            292             48       0     1   
1            1    1            3            292             48       0     1   
2            0    1            3            218             48       1     1   
3            1    0            3            169             48       1     2   
4            0    0            3             20             48       0     0   

   coat_length  good_with_children  good_with_dogs  good_with_cats  \
0            5                   0               1               0   
1            4                   1               1               0   
2            3                   1               1               1   
3            3                   1               1               1   
4            4                   0               0               0   

   good_with_other_animals  house_trained  altered  declawed  special_needs  \
0                        0              0        1         0              1   
1                        0              0        1         0              0   
2                        0              1        1         0              0   
3                        0              0        0         0              0   
4                        0              0        0         0              0   

   shots_current  num_photos  num_videos  has_description  
0              1           5           0                1  
1              1           2           0                1  
2              1           6           0                1  
3              1           1           0                1  
4              0           3           0                0

In [11]:
print (len(df), "pets")
print (len(df.columns), "features")

63307 pets
20 features


In [12]:
# convert each row of the dataframe into an array
pets = df.values

def input_fn():
  return tf.compat.v1.train.limit_epochs(
      tf.convert_to_tensor(pets, dtype=tf.float32), num_epochs=10)

num_clusters = 10
kmeans = tf.compat.v1.estimator.experimental.KMeans(
    num_clusters=num_clusters, use_mini_batch=False)

# train
num_iterations = 10
previous_centers = None
for _ in range(num_iterations):
    kmeans.train(input_fn)
    cluster_centers = kmeans.cluster_centers()
    if previous_centers is not None:
        print('DELTA:', cluster_centers - previous_centers)
    previous_centers = cluster_centers
    print('SCORE:', kmeans.score(input_fn))
    print("--------FINISHED 1 ITERATION--------")
print ('final cluster centers:', cluster_centers)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/var/folders/2_/_8xm9cb17rx3dn7qvpx_9g6c0000gp/T/tmp5qlpmtwm', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
Instructions for updating:
If using Keras pass *_constraint arguments to 

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2020-07-09T22:57:58Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/2_/_8xm9cb17rx3dn7qvpx_9g6c0000gp/T/tmp5qlpmtwm/model.ckpt-21
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1/1]
INFO:tensorflow:Inference Time : 0.20493s
INFO:tensorflow:Finished evaluation at 2020-07-09-22:57:58
INFO:tensorflow:Saving dict for global step 21: global_step = 21, loss = 54278172.0, score = 54278172.0
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 21: /var/folders/2_/_8xm9cb17rx3dn7qvpx_9g6c0000gp/T/tmp5qlpmtwm/model.ckpt-21
SCORE: 54278172.0
--------FINISHED 1 ITERATION--------
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters fr

INFO:tensorflow:Saving 'checkpoint_path' summary for global step 54: /var/folders/2_/_8xm9cb17rx3dn7qvpx_9g6c0000gp/T/tmp5qlpmtwm/model.ckpt-54
SCORE: 54278172.0
--------FINISHED 1 ITERATION--------
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/2_/_8xm9cb17rx3dn7qvpx_9g6c0000gp/T/tmp5qlpmtwm/model.ckpt-54
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 54...
INFO:tensorflow:Saving checkpoints for 54 into /var/folders/2_/_8xm9cb17rx3dn7qvpx_9g6c0000gp/T/tmp5qlpmtwm/model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 54...
INFO:tensorflow:loss = 54278172.0, step = 55
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 65...
INFO:tensorflow:Saving checkpoints for 65 into /var/fol

INFO:tensorflow:Saving checkpoints for 98 into /var/folders/2_/_8xm9cb17rx3dn7qvpx_9g6c0000gp/T/tmp5qlpmtwm/model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 98...
INFO:tensorflow:Loss for final step: 54278172.0.
DELTA: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2020-0

In [63]:
# map each pet to their clusters
cluster_indices = list(kmeans.predict_cluster_index(input_fn))
output = {
    "0": {"breeds": {}},
    "1": {"breeds": {}},
    "2": {"breeds": {}},
    "3": {"breeds": {}},
    "4": {"breeds": {}},
    "5": {"breeds": {}},
    "6": {"breeds": {}},
    "7": {"breeds": {}},
    "8": {"breeds": {}},
    "9": {"breeds": {}},
}
for i, pet_data in enumerate(pets):
    cluster = str(cluster_indices[i])
    breed = breed_enc.inverse_transform([pet_data[3]])[0]
    # add to output dictionary
    if breed in output[cluster]["breeds"]: 
        output[cluster]["breeds"][breed] += 1
    else:
        output[cluster]["breeds"][breed] = 1

import json
with open('clusters.json', 'w') as fp:
    json.dump(output, fp)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/2_/_8xm9cb17rx3dn7qvpx_9g6c0000gp/T/tmp5qlpmtwm/model.ckpt-109
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
